x-logging: &logging
  options:
    max-size: "256k"
    max-file: "1"
  driver: json-file

services:

  reverse-proxy:
    restart: always
    build:
      context: ./services/reverse-proxy
    environment:
      - UI_BASE_URI=$UI_BASE_URI
      - API_BASE_URI=$API_BASE_URI
    ports:
      - "${HOST_IP}:80:80"
      - "${HOST_IP}:443:443"
    volumes:
      - certbot-dist:/etc/letsencrypt/:ro
      - certbot-www:/var/www/certbot:ro
    logging: *logging

  certbot:
    restart: always
    build:
      context: ./services/certbot
    volumes:
      - certbot-dist:/etc/letsencrypt/:rw
      - certbot-www:/var/www/certbot:rw
    environment:
      - DOMAINS=$DOMAIN_NAME
      - EMAIL=$CERTBOT_EMAIL
      - CERT_MODE=prod
    logging: *logging
    # deploy: { replicas: 0 }

  ui:
    build:
      context: ./services/ui
      network: host
      args:
        - BASE_URI=$UI_BASE_URI
    restart: always
    logging: *logging
    networks:
      default:
        ipv4_address: "172.25.1.101"
    environment:
      - API_BASE_URI=$API_BASE_URI

  backend:
    build:
      context: ./services/backend
      network: host
    restart: always
    logging: *logging
    stop_signal: SIGKILL
    networks:
      default:
        ipv4_address: "172.25.1.102"
    environment:
      - "POSTGRES_HOST=postgres"
      - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
      - "POSTGRES_USER=$POSTGRES_USER"
      - "POSTGRES_DB=$POSTGRES_DB"

  researcher:
    build:
      context: ./services/researcher
      network: host
    restart: always
    logging: *logging

  postgres:
    build:
      context: ./services/postgres
    restart: always
    # shm_size: 128mb
    environment:
      - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
      - "POSTGRES_USER=$POSTGRES_USER"
      - "POSTGRES_DB=$POSTGRES_DB"
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"
          gateway: "172.25.0.1"

volumes:
  certbot-dist:
  certbot-www:
  postgres-data:
